# Generated by Django 4.2 on 2026-06-13 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.IntegerField()),
                ("communication_score", models.IntegerField()),
                ("technical_score", models.IntegerField()),
                ("confidence_score", models.IntegerField()),
                ("strengths", models.TextField()),
                ("weaknesses", models.TextField()),
                ("feedback", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interviews.interviewsession",
                    ),
                ),
            ],
        ),
    ]
