# Generated by Django 4.2 on 2026-06-13 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("resumes", "0001_initial"),
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="resumes.resumes",
            ),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="resume_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resumes.resumes"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="interviews.question"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="interviews.interviewsession",
            ),
        ),
    ]
